export { default as IconKorean } from '@/assets/icons/food-category/korean.svg';
export { default as IconChinese } from '@/assets/icons/food-category/chinese.svg';
export { default as IconJapanese } from '@/assets/icons/food-category/japanese.svg';
export { default as IconWestern } from '@/assets/icons/food-category/western.svg';
export { default as IconFastFood } from '@/assets/icons/food-category/fast_food.svg';
export { default as IconMeatDishes } from '@/assets/icons/food-category/meat_dishes.svg';
// export { default as IconSoupAndStew } from '@/assets/icons/food-category/soup_and_stew.svg';
// export { default as IconNoodles } from '@/assets/icons/food-category/noodles.svg';
// export { default as IconSnackFood } from '@/assets/icons/food-category/snack_food.svg';
export { default as IconGlobalFood } from '@/assets/icons/food-category/global_food.svg';
export { default as IconPubAndBar } from '@/assets/icons/food-category/pub_and_bar.svg';
export { default as IconDesserts } from '@/assets/icons/food-category/desserts.svg';
